name: aqary_assesment_project
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^8.0.1
  graphql_flutter: ^5.0.0
  equatable: ^2.0.3
  web_socket_channel:
  flutter_dotenv:

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  bloc_test: ^9.0.3

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - .env
